version: "3"

services:
  broker-mqtt:
    image: eclipse-mosquitto:1.6
    ports:
      - "9002:9001"
      - "1883:1883"
    volumes:
      - MQTT_VOLUME:/mosquitto/data            

  # api-gateway:
  #   build: ./apiGateway
  #   ports:
  #     - "5200:5200"

  catalog-mongo-db:
    image: mongo:4
    ports:
      - "27018:27017"
    environment: 
        - storageEngine=wiredTiger
    volumes: 
      - CATALOG_MONGO_VOLUME:/data/db

  offer-mongo-db:
    image: mongo:4
    ports:
      - "27019:27017"
    environment: 
      - storageEngine=wiredTiger
    volumes: 
      - OFFER_MONGO_VOLUME:/data/db

  store-mongo-db:
    image: mongo:4
    ports:
      - "27020:27017"
    environment: 
      - storageEngine=wiredTiger
    volumes: 
      - STORE_MONGO_VOLUME:/data/db   

  grafana:
    image: grafana/grafana:8.0.6
    container_name: grafana
    restart: unless-stopped
    volumes:
    - GRAFANA_DATA:/var/lib/grafana
    ports:
    - 3000:3000

  prometheus:
    image: prom/prometheus:v2.28.1
    container_name: prometheus
    restart: unless-stopped
    volumes:
    - ./prometheus.yml:/etc/prometheus/prometheus.yml
    - PROMETHEUS_DATA:/prometheus
    ports:
    - 9090:9090
    command:
    - '--config.file=/etc/prometheus/prometheus.yml'
    - '--storage.tsdb.path=/prometheus'
    - '--storage.tsdb.retention.time=1y'
    - '--web.enable-lifecycle'
  

  node_exporter:
    image: quay.io/prometheus/node-exporter:latest
    container_name: node_exporter
    restart: unless-stopped
    ports:
    - 9100:9100
    command:
    - '--path.rootfs=/host'
    pid: host
    volumes:
    - ./NODE_EXPORTER:/host
        
volumes: 
  MQTT_VOLUME:
  CATALOG_MONGO_VOLUME:
  OFFER_MONGO_VOLUME:
  # AUTH_MONGO_VOLUME:
  STORE_MONGO_VOLUME:
  GRAFANA_DATA:
  PROMETHEUS_DATA:
  NODE_EXPORTER:
