version: "3"

services:
  broker-mqtt:
    image: eclipse-mosquitto:1.6
    ports:
      - "9001:9001"
      - "1883:1883"
    volumes:
      - MQTT_VOLUME:/mosquitto/data            
  store-mongo:
    image: mongo:4
    ports:
      - "27018:27017"
    environment: 
        - storageEngine=wiredTiger
    volumes: 
      - MONGO_VOLUME:/data/db
volumes: 
  MQTT_VOLUME:
  MONGO_VOLUME: