
type ProductObject {
    ref: String
    name: String
    price: Float
    description: String
    inOffer: Boolean
    discount: Float
}

input CarInput{
    brand: String
    km: Int
    owner: String
    model: String
}

input ProductInput {
    ref: String
    name: String
    price: Float
    description: String
    inOffer: Boolean
    discount: Float
}

input OfferInput {
    products: [ProductInput],
    date: String
}

input CatalogInput {
  products: [ProductInput]
  offers: [OfferInput]
}

"Consultas de la información de los precios. Solo lectura"
type Query {
    "Lista de los estudiantes de la academia"
    msCatalogSearchCatalogByStoreId(storeId: String!): Catalog,
    products(catalogId: String): String,
    searchProduct(keyword: String): [ProductObject]
    removeProductFromCatalog(catalogId: String, productId: String): String

}

type Mutation{
    createProduct(productInput: ProductInput): MutationResult
    editProduct(productInput: ProductInput): MutationResult
    deleteProduct(productRef: String): MutationResult
    createCatalog(catalogInput: CatalogInput): MutationResult
}
